### ISSUE TITLE
when did that changed?

### ISSUE THREAD

**Issue by meleu** [cmitu/mkdocs-altlink-plugin#3]
Hi @cmitu 

(First: sorry for opening an issue here just to reach you. Please close it as soon as you read it.)

In the early 2018 I implemented the [RetroAchievements documentation](https://docs.retroachievements.org/) highly influenced by the techniques used by @HerbFargus and @joolswills for the RetroPie docs: get the pages from the wiki, and then generate the site with mkdocs.

And I remember we didn't need the thing you're doing in this plugin.

Do you know when the mkdocs behavior have changed?

**Comment by cmitu** [comment]
Probably around 1.0 ? 
We noticed this last year, after a report from the forums, and we temporarily reverted back in https://github.com/RetroPie/RetroPie-Setup/commit/92ada70d3847eaff42bf0f95b78701f1abf37b44 (so mkdocs `0.17.5` was ok).  This extension was specifically crafted to tackle the stricter link requirements in the new versions and to be able to use `mkdocs` without converting all the links in the Wiki.

**Comment by meleu** [comment]
Gotcha!

Thank you very much for your work to resolve this.

And those warnings about the broken links are really fine! 👌 

I'm definitely going to use your plugin on my setup.
